# -*- coding: utf-8 -*-
"""project-src.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ds_1m89-oKnQNWRMNN-06PSF5__g5dKo
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **Early diabetes diagnosis**"""

import os
import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

data_path = "/content/drive/MyDrive/project/diabetes_data_upload.csv"

actual_patient_data = pd.read_csv(data_path)
actual_patient_data.head()

actual_patient_data['class'].value_counts()

converted_data=pd.get_dummies(actual_patient_data, prefix=['Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss',
       'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring',
       'Itching', 'Irritability', 'delayed healing', 'partial paresis',
       'muscle stiffness', 'Alopecia', 'Obesity', 'class'], drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(converted_data.drop('class_Positive', axis=1),converted_data['class_Positive'], test_size=0.3, random_state=0)

classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
from sklearn import metrics
acc = metrics.accuracy_score(y_test, y_pred)

print(f"Accuracy score is: {acc}")

os.makedirs('/content/drive/My Drive/project/models', exist_ok=True)

joblib.dump(classifier, os.path.join(folder_path, 'diabetes_early_stage.pkl'))
